import { Metadata } from "next"
import HeroSection from "@/components/Pages/(marketing)/home/hero"
import ProductCard from "@/components/Pages/(marketing)/home/product-card"
import { Products } from "@/context/products"
import Loading from "./loading"

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
}

export default function Home() {
  return (
    <main className="container">
      <HeroSection />

      <section>
        <h3>Featured Products</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 py-4 sm:py-6 lg:py-8">
          {Products.map((product, i) => (
            <ProductCard data={product} key={i} />
          ))}
        </div>
      </section>
    </main>
  )
}
