import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Shadcn Lebanese E-commerce",
  description: "Generated by create next app",
}

export default function Home() {
  return <main className="flex flex-col items-center justify-between p-24">Hello</main>
}
