import { Metadata } from 'next'
import HeroSection from '@/components/Pages/(marketing)/home/hero'

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function Home() {
    return (
        <main className="container">
            <HeroSection />
        </main>
    )
}
