import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
}

const DashboardPage = () => {
  return <div>DashboardPage</div>
}

export default DashboardPage
