import "@/styles/globals.css"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { TailwindIndicator } from "@/components/ui/tailwind-indicator"
import NavigationBar from "@/components/NavFluid"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Shadcn Lebanese E-commerce",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <NavigationBar />
        {children}
        <TailwindIndicator />
      </body>
    </html>
  )
}
