import { Metadata } from "next"
import axiosApi from "@/lib/axios"
import { ProductModel } from "@/types/ProductModel"
import { BillboardModel } from "@/types/BillboardModel"
import HeroSection from "@/components/Pages/home/hero"
import ProductCard from "@/components/Pages/home/product-card"

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
}

const getBillboards = async () => {
  try {
    const res = await axiosApi.get("/billboards?isActive=true")
    return res.data
  } catch (error) {
    console.log(error)
  }
}
const getFeaturedDrinks = async () => {
  try {
    const res = await axiosApi.get("/products?isFeatured=true&categoryId=f7a2870e-e968-481d-b2b0-ffe9f8928e2c")
    return res.data
  } catch (error) {
    console.log(error)
  }
}
const getFeaturedChicken = async () => {
  try {
    const res = await axiosApi.get("/products?isFeatured=true&categoryId=22933449-ecb4-407f-9792-5abd601f78c0")
    return res.data
  } catch (error) {
    console.log(error)
  }
}

export default async function Home() {
  const billboards = (await getBillboards()) as BillboardModel[]
  const featuredDrinks = (await getFeaturedDrinks()) as ProductModel[]
  const featuredChicken = (await getFeaturedChicken()) as ProductModel[]

  return (
    <main className="container">
      <HeroSection billboards={billboards} />

      <section>
        <h3>Featured Drinks</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 py-4 sm:py-6 lg:py-8">
          {featuredDrinks.map((product, i) => (
            <ProductCard data={product} key={i} />
          ))}
        </div>
        <h3>Featured Chicken</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 py-4 sm:py-6 lg:py-8">
          {featuredChicken.map((product, i) => (
            <ProductCard data={product} key={i} />
          ))}
        </div>
      </section>
    </main>
  )
}
